### PR TITLE
Task1: really-ugly-json.json 代码风格重构

### LINKED ISSUE #16: [T.4] Task 1
- RedCinnamoroll/Red-VCS/pull/8

### PR DESCRIPTION
**Pull request by Toby-Shi-cloud**
## Task1

really-ugly-json.json 代码风格重构

### CODE REVIEW

**Comment by Toby-Shi-cloud** [comment]
https://github.com/orgs/RedCinnamoroll/projects/2/views/1?pane=issue&itemId=59111517

**Comment by Toby-Shi-cloud** [comment]
solve https://github.com/orgs/RedCinnamoroll/projects/2/views/1?pane=issue&itemId=59111517

**Comment by Toby-Shi-cloud** [comment]
resolve #16

**Review by Star-Feel — APPROVED** [review]
Approved

**Pull request merged**
